// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBASzUrsjMnohupeGRO-iqQWzMbfAGsNpI',
    appId: '1:178939725342:web:fbe9e93e27590459a8100f',
    messagingSenderId: '178939725342',
    projectId: 'taller-firebase-universidades',
    authDomain: 'taller-firebase-universidades.firebaseapp.com',
    storageBucket: 'taller-firebase-universidades.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz_jqrb9lJnz7KCro8RJ9ggrS58jV86wU',
    appId: '1:178939725342:android:1863a723509eab2ea8100f',
    messagingSenderId: '178939725342',
    projectId: 'taller-firebase-universidades',
    storageBucket: 'taller-firebase-universidades.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvYB7VYsD6Ci7c5OiCOWMzaeelyLZq46o',
    appId: '1:178939725342:ios:e1ec27460f7c6872a8100f',
    messagingSenderId: '178939725342',
    projectId: 'taller-firebase-universidades',
    storageBucket: 'taller-firebase-universidades.firebasestorage.app',
    iosBundleId: 'com.example.cursoMoviles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvYB7VYsD6Ci7c5OiCOWMzaeelyLZq46o',
    appId: '1:178939725342:ios:e1ec27460f7c6872a8100f',
    messagingSenderId: '178939725342',
    projectId: 'taller-firebase-universidades',
    storageBucket: 'taller-firebase-universidades.firebasestorage.app',
    iosBundleId: 'com.example.cursoMoviles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBASzUrsjMnohupeGRO-iqQWzMbfAGsNpI',
    appId: '1:178939725342:web:d343d8bc67ca3830a8100f',
    messagingSenderId: '178939725342',
    projectId: 'taller-firebase-universidades',
    authDomain: 'taller-firebase-universidades.firebaseapp.com',
    storageBucket: 'taller-firebase-universidades.firebasestorage.app',
  );
}
